FROM python:3.8-slim

WORKDIR /app
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/drugapp/networkmodel.py .
COPY app/drugapp/platform.py .
COPY app/drugapp/filepaths.py .

RUN pip install xgboost scikit-learn node2vec networkx matplotlib

COPY app/drugapp/data drugapp/data
RUN mkdir -p drugapp/data/reference
ENV PYTHONUNBUFFERED=1
CMD ["python", "-c", "from drugapp.networkmodel import run_network_model; run_network_model()"]